name: GitHub Issue Enhancer

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  enhance-issue:
    name: GitHub Issue Enhancer
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Enhancer
        uses: JustJade2007/github-issue-enhancer@1.0.0
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
